[package]
name = "hole-punching"
version = "0.1.0"
authors = ["unishift <unishifft@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
clap = "3.0.0-beta.1"
